/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Login.Compoment;

import com.app.hrm.Entity.NhanVien;
import com.app.hrm.Utils.Auth;
import com.app.hrm.Utils.XImage;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.RenderingHints;
import java.awt.event.ActionListener;
import java.awt.geom.Path2D;
import javax.swing.ImageIcon;
import org.jdesktop.animation.timing.Animator;
import org.jdesktop.animation.timing.TimingTarget;
import org.jdesktop.animation.timing.TimingTargetAdapter;

/**
 *
 * @author ADMIN
 */
public class PanelLoading extends javax.swing.JLayeredPane {

    private final Animator animator;
    private boolean slideLeft;
    private float animate;
    private boolean isMessage;
   

    /**
     * Creates new form PanelLoading
     */
    public PanelLoading() {
        initComponents();
        loading.setVisible(true);
        Avatar.setVisible(false);
        Mess.setVisible(false);
        TimingTarget target = new TimingTargetAdapter() {
            @Override
            public void begin() {
                if (isMessage) {
                    Mess.setVisible(true);
                } else {
                    Avatar.setVisible(true);
                }
            }

            @Override
            public void timingEvent(float fraction) {
                if (isMessage) {
                    Mess.setAlpha(fraction);
                    loading.setAlpha(1f - fraction);
                } else {
                    Avatar.setAlpha(fraction);
                    loading.setAlpha(1f - fraction);
                }
                repaint();
            }
        };
        animator = new Animator(500, target);
        animator.setResolution(0);
    
    }

    public void setAnimate(boolean slideLeft, float animate) {
        this.slideLeft = slideLeft;
        this.animate = animate;
    }

    public void addEventBack(ActionListener event) {
        btnHuy.addActionListener(event);
        btnHuy1.addActionListener(event);
        btnHuy2.addActionListener(event);

    }

    public void addEventContinue(ActionListener event) {
        btnTT.addActionListener(event);
    }

    public void doneLogin(NhanVien nv) {
        isMessage = false;
        ImageIcon icon = null;
        Auth.user = nv;
        if(nv.getHinh().trim().equals("")){
            icon = XImage.read("100.png");
        }else{
             icon = XImage.read(nv.getHinh());
        }
       lblTen.setText(nv.getHoTen());
        iAvatar.setImage(icon);
        btnTT.setText("Tiếp tục đăng nhập");
        animator.start();
    }

    public void showError(String ms) {
        lblMess.setText(ms);
        isMessage = true;
        animator.start();
    }

    public void reset() {
        loading.setAlpha(1f);
        loading.setVisible(true);
        iAvatar.setVisible(false);
        Mess.setVisible(false);
    }
    
    public void clear(){
        ImageIcon icon = XImage.read("100.png");
        iAvatar.setImage(icon);
        lblTen.setText("");
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Avatar = new Swing.PanelTransparent();
        btnHuy2 = new Swing.Button();
        iAvatar = new Swing.ImageAvatar();
        lblTen = new javax.swing.JLabel();
        btnTT = new Swing.Button();
        Mess = new Swing.PanelTransparent();
        btnHuy1 = new Swing.Button();
        lblMess = new javax.swing.JLabel();
        loading = new Swing.PanelTransparent();
        btnHuy = new Swing.Button();
        jLabel1 = new javax.swing.JLabel();

        setLayout(new java.awt.CardLayout());

        btnHuy2.setBackground(new java.awt.Color(67, 99, 132));
        btnHuy2.setForeground(new java.awt.Color(255, 255, 255));
        btnHuy2.setText("Hủy");
        btnHuy2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        iAvatar.setBorderSize(3);
        iAvatar.setBorderSpace(2);

        lblTen.setBackground(new java.awt.Color(67, 99, 132));
        lblTen.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblTen.setForeground(new java.awt.Color(255, 255, 255));
        lblTen.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTen.setText("Tên nhân viên");
        lblTen.setOpaque(true);

        btnTT.setBackground(new java.awt.Color(67, 99, 132));
        btnTT.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
        btnTT.setForeground(new java.awt.Color(255, 255, 255));
        btnTT.setText("Tiếp tục");
        btnTT.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        javax.swing.GroupLayout AvatarLayout = new javax.swing.GroupLayout(Avatar);
        Avatar.setLayout(AvatarLayout);
        AvatarLayout.setHorizontalGroup(
            AvatarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AvatarLayout.createSequentialGroup()
                .addContainerGap(100, Short.MAX_VALUE)
                .addComponent(iAvatar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(100, 100, 100))
            .addGroup(AvatarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(AvatarLayout.createSequentialGroup()
                .addGroup(AvatarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(AvatarLayout.createSequentialGroup()
                        .addGap(120, 120, 120)
                        .addComponent(btnHuy2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(AvatarLayout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(btnTT, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        AvatarLayout.setVerticalGroup(
            AvatarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AvatarLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(iAvatar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblTen)
                .addGap(20, 20, 20)
                .addComponent(btnTT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 89, Short.MAX_VALUE)
                .addComponent(btnHuy2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32))
        );

        add(Avatar, "card2");

        btnHuy1.setBackground(new java.awt.Color(67, 99, 132));
        btnHuy1.setForeground(new java.awt.Color(255, 255, 255));
        btnHuy1.setText("Hủy");
        btnHuy1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        lblMess.setBackground(new java.awt.Color(67, 99, 132));
        lblMess.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblMess.setForeground(new java.awt.Color(255, 51, 51));
        lblMess.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblMess.setText("Tin nhắn");
        lblMess.setOpaque(true);

        javax.swing.GroupLayout MessLayout = new javax.swing.GroupLayout(Mess);
        Mess.setLayout(MessLayout);
        MessLayout.setHorizontalGroup(
            MessLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MessLayout.createSequentialGroup()
                .addGap(120, 120, 120)
                .addComponent(btnHuy1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(120, Short.MAX_VALUE))
            .addGroup(MessLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblMess, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        MessLayout.setVerticalGroup(
            MessLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MessLayout.createSequentialGroup()
                .addContainerGap(169, Short.MAX_VALUE)
                .addComponent(lblMess, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(143, 143, 143)
                .addComponent(btnHuy1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32))
        );

        add(Mess, "card2");

        btnHuy.setBackground(new java.awt.Color(67, 99, 132));
        btnHuy.setForeground(new java.awt.Color(255, 255, 255));
        btnHuy.setText("Hủy");
        btnHuy.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/app/hrm/icon/loading.gif"))); // NOI18N

        javax.swing.GroupLayout loadingLayout = new javax.swing.GroupLayout(loading);
        loading.setLayout(loadingLayout);
        loadingLayout.setHorizontalGroup(
            loadingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loadingLayout.createSequentialGroup()
                .addGap(120, 120, 120)
                .addComponent(btnHuy, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(loadingLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(30, 30, 30))
        );
        loadingLayout.setVerticalGroup(
            loadingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, loadingLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 282, Short.MAX_VALUE)
                .addGap(30, 30, 30)
                .addComponent(btnHuy, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32))
        );

        add(loading, "card2");
    }// </editor-fold>//GEN-END:initComponents

    @Override
    public void paint(Graphics grphcs) {
        Graphics2D g2 = (Graphics2D) grphcs.create();
        g2.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);
        g2.setColor(getBackground());
        int width = getWidth();
        int height = getHeight();
        int x = 0;
        int y = 0;
        if (slideLeft) {
            int centerY = height / 2;
            Path2D.Float p = new Path2D.Float();
            p.moveTo(x, y);
            p.lineTo(width, y);
            p.lineTo(width, height);
            p.lineTo(x, height);
            p.curveTo(x, height, easeOutBounce(animate) * width, centerY, x, y);
            g2.fill(p);
        } else {
            g2.fillRect(x, y, width, height);
        }
        g2.dispose();
        super.paint(grphcs);
    }

    private float easeOutBounce(float x) {
        float n1 = 7.5625f;
        float d1 = 2.75f;
        double v;
        if (x < 1 / d1) {
            v = n1 * x * x;
        } else if (x < 2 / d1) {
            v = n1 * (x -= 1.5 / d1) * x + 0.75;
        } else if (x < 2.5 / d1) {
            v = n1 * (x -= 2.25 / d1) * x + 0.9375;
        } else {
            v = n1 * (x -= 2.625 / d1) * x + 0.984375;
        }
        if (slideLeft) {
            return (float) (1f - v);
        } else {
            return (float) v;
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private Swing.PanelTransparent Avatar;
    private Swing.PanelTransparent Mess;
    private Swing.Button btnHuy;
    private Swing.Button btnHuy1;
    private Swing.Button btnHuy2;
    private Swing.Button btnTT;
    private Swing.ImageAvatar iAvatar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblMess;
    private javax.swing.JLabel lblTen;
    private Swing.PanelTransparent loading;
    // End of variables declaration//GEN-END:variables
}
